"""Deterministic EVA calculation.

Kept completely separate from the AI layer on purpose: the numbers that
decide a company's financial standing should never be generated by an
LLM. The AI only *interprets* and *narrates* a result that Python has
already computed.

Formula (per brief):
    NOPAT = EBIT * (1 - Tax Rate)
    Capital Charge = Invested Capital * WACC
    EVA = NOPAT - Capital Charge
"""

from app.schemas import EvaResult, FinancialInput


def calculate_eva(data: FinancialInput) -> EvaResult:
    nopat = data.ebit * (1 - data.tax_rate)
    capital_charge = data.invested_capital * data.wacc
    eva = nopat - capital_charge

    if eva > 0:
        status = "positif"
    elif eva == 0:
        status = "impas"
    else:
        status = "negatif"

    return EvaResult(
        company_name=data.company_name,
        period=data.period,
        nopat=round(nopat, 2),
        capital_charge=round(capital_charge, 2),
        eva=round(eva, 2),
        status=status,
    )
